#!/usr/bin/env python3
"""gen_duel_tables.py DUEL.EXE OUT.c: writes the duel's data tables as C, from an EXEPACK-unpacked DUEL.EXE.

The tables live in DUEL's data segment (DS = 162A, i.e. file offset 0x66A0 + DS offset in the unpacked
file): the animation state table (DS:0A8C, 133 x 24 bytes), the move table (DS:1704, 6-byte rows ended
by -1), the AI response table (DS:17B2, 50-byte rows ended by -1) and the AI's no-parry masks (DS:1E64).
"""
import struct, sys

exe, out = sys.argv[1], sys.argv[2]
d = open(exe, 'rb').read()
hdr = struct.unpack_from('<H', d, 8)[0] * 16
DS = hdr + (0x162A - 0x1000) * 16
assert d[DS + 0x42:DS + 0x4A] == b'duel.cat', 'not the 445.03 DUEL.EXE (unpacked)'


def w(off): return struct.unpack_from('<h', d, DS + off)[0]


L = ['// Generated by tools/gen_duel_tables.py from DUEL.EXE (445.03); do not edit.', '#include "duel.h"', '']
L.append('const DuelStateEntry duel_states[DUEL_STATE_COUNT] = {')
for i in range(133):
    b = DS + 0x0A8C + 24 * i
    tops, legs, hold, xoff, yoff, a, c = struct.unpack_from('<7h', d, b)
    auto = struct.unpack_from('<b', d, b + 14)[0]
    nxt = struct.unpack_from('<9b', d, b + 15)
    L.append(f'  {{ {tops}, {legs}, {hold}, {xoff}, {yoff}, {a}, {c}, {auto}, {{ {", ".join(map(str, nxt))} }} }}, // 0x{i:02X}')
L.append('};')
L.append('')
rows = []
off = 0x1704
while w(off) != -1:
    rows.append((w(off), w(off + 2), w(off + 4))); off += 6
L.append(f'const DuelMove duel_moves[{len(rows) + 1}] = {{')
for s, dx, dy in rows: L.append(f'  {{ 0x{s:02X}, {dx}, {dy} }},')
L.append('  { -1, 0, 0 },')
L.append('};')
L.append('')
ai = []
off = 0x17B2
while w(off) != -1:
    ai.append([w(off)] + [w(off + 2 + 2 * k) for k in range(24)]); off += 50
L.append(f'const DuelAiRow duel_ai[{len(ai) + 1}] = {{')
for r in ai: L.append(f'  {{ 0x{r[0]:02X}, {{ {", ".join("0x%02X" % (v & 0xFFFF) if v >= 0 else str(v) for v in r[1:])} }} }},')
L.append('  { -1, { 0 } },')
L.append('};')
L.append('')
L.append('const uint16_t duel_noparry_masks[4] = { ' + ', '.join('0x%04X' % (w(0x1E64 + 2 * k) & 0xFFFF) for k in range(4)) + ' };')
open(out, 'w').write('\n'.join(L) + '\n')
print(out, len(rows), 'moves', len(ai), 'AI rows')
