#!/usr/bin/env python3
"""gen_battle_tables.py BATTLE.EXE OUT.c: writes BATTLE.EXE's initialised tables (DS:0000-1B27) as C.

From an EXEPACK-unpacked BATTLE.EXE (445.03): DS = 193D, i.e. file offset header + 0x93D0. The block holds
the unit state handler table, the men scales and variant thresholds, the six formation tables, the unit
type table, the figure geometry, the damage tables, scan directions and ray penalties, sprite bases, the
melee jitter, the terrain textures and border program and the sine table (DS:18B2, 257 words).
"""
import struct, sys

exe, out = sys.argv[1], sys.argv[2]
d = open(exe, 'rb').read()
hdr = struct.unpack_from('<H', d, 8)[0] * 16
DS = hdr + (0x193D - 0x1000) * 16
assert d[DS + 0x16C0:DS + 0x16C9] == b'ICONS.PIC', 'not the 445.03 BATTLE.EXE (unpacked)'
blob = d[DS:DS + 0x1B28]
L = ['// Generated by tools/gen_battle_tables.py from BATTLE.EXE (445.03); do not edit.', '#include "battle.h"', '',
     'const uint8_t battle_tables[BATTLE_TABLES_SIZE] = {']
for i in range(0, len(blob), 24):
    L.append('  ' + ', '.join('0x%02X' % b for b in blob[i:i + 24]) + ',')
L.append('};')
L.append('')
L.append('const int16_t *battle_sine = (const int16_t *)(battle_tables + 0x18B2);')
open(out, 'w').write('\n'.join(L) + '\n')
print(out, len(blob), 'bytes')
